//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace goatMGMT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnimalTreatment
    {
        public int animal_id { get; set; }
        public int treatment_id { get; set; }
        public System.DateTime date_applied { get; set; }
        public string details { get; set; }
        public string product { get; set; }
        public string dosage { get; set; }
        public string remarks { get; set; }
        public Nullable<int> Animals_id { get; set; }
        public Nullable<System.DateTime> Animals_dob { get; set; }
        public Nullable<int> Animals_farm_name { get; set; }
        public Nullable<int> Treatments_id { get; set; }
    
        public virtual Animal Animal { get; set; }
        public virtual Treatment Treatment { get; set; }
    }
}
