//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace goatMGMT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Animal()
        {
            this.AnimalTreatments = new HashSet<AnimalTreatment>();
            this.Births = new HashSet<Birth>();
            this.Births1 = new HashSet<Birth>();
            this.Births2 = new HashSet<Birth>();
            this.Breedings = new HashSet<Breeding>();
            this.Breedings1 = new HashSet<Breeding>();
        }
    
        public int id { get; set; }
        public int owner { get; set; }
        public string tag { get; set; }
        public System.DateTime dob { get; set; }
        public bool sex { get; set; }
        public string status_code { get; set; }
        public bool isChild { get; set; }
        public string breed_code { get; set; }
        public string name { get; set; }
        public string regulation_no { get; set; }
        public string microchip_id { get; set; }
        public string premise_id { get; set; }
        public string herd_id_code { get; set; }
        public string breed_registry { get; set; }
        public string species { get; set; }
        public Nullable<double> current_weight { get; set; }
        public Nullable<double> weaning_weight { get; set; }
        public Nullable<System.DateTime> weaning_date { get; set; }
        public Nullable<double> market_weight { get; set; }
        public Nullable<System.DateTime> market_date { get; set; }
        public Nullable<System.DateTime> disposal_date { get; set; }
        public string remarks { get; set; }
        public Nullable<int> owner1 { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnimalTreatment> AnimalTreatments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Birth> Births { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Birth> Births1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Birth> Births2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Breeding> Breedings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Breeding> Breedings1 { get; set; }
    }
}
