//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace goatMGMT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Birth
    {
        public int id { get; set; }
        public int child_id { get; set; }
        public int mother_id { get; set; }
        public int father_id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<int> parity { get; set; }
        public Nullable<int> score { get; set; }
        public Nullable<int> alive { get; set; }
        public Nullable<int> born { get; set; }
        public string notes { get; set; }
    
        public virtual Animal Animal { get; set; }
        public virtual Animal Animal1 { get; set; }
        public virtual Animal Animal2 { get; set; }
    }
}
