//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace goatMGMT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Breeding
    {
        public int id { get; set; }
        public int mother_id { get; set; }
        public int father_id { get; set; }
        public System.DateTime date { get; set; }
        public string remarks { get; set; }
        public Nullable<int> father_id1 { get; set; }
        public Nullable<System.DateTime> father_dob { get; set; }
        public Nullable<int> father_farm_name { get; set; }
        public Nullable<int> mother_id1 { get; set; }
        public Nullable<System.DateTime> mother_dob { get; set; }
        public Nullable<int> mother_farm_name { get; set; }
    
        public virtual Animal Animal { get; set; }
        public virtual Animal Animal1 { get; set; }
    }
}
