//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace goatMGMT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int id { get; set; }
        public Nullable<System.DateTime> date_sent { get; set; }
        public string name { get; set; }
        public string subject { get; set; }
        public string email { get; set; }
        public string comment1 { get; set; }
    }
}
