//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace goatMGMT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int id { get; set; }
        public string item_detail { get; set; }
        public string item_type { get; set; }
        public Nullable<decimal> quantity { get; set; }
        public Nullable<decimal> unit_Price { get; set; }
        public Nullable<decimal> total_Payment { get; set; }
        public string notes { get; set; }
    }
}
