//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace goatMGMT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Treatment
    {
        public int id { get; set; }
        public int animal_id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string item_type { get; set; }
        public string product { get; set; }
        public string dosage { get; set; }
        public string remarks { get; set; }
    
        public virtual Animal Animal { get; set; }
    }
}
